// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function GetData():Promise<handler.GetDataResponse>;

export function Greet(arg1:string):Promise<string>;
