// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData() {
  return window['go']['handler']['Handler']['GetData']();
}

export function Greet(arg1) {
  return window['go']['handler']['Handler']['Greet'](arg1);
}
